name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          10.0.x

    - name: Restore dependencies
      run: dotnet restore CarSparePartSys.sln

    - name: Build Solution
      run: dotnet build CarSparePartSys.sln --no-restore -c Release

    - name: Run Unit Tests
      run: dotnet test CarSparePartSys.sln --no-build -c Release --verbosity normal
